import type { ServiceContent } from "@/components/service/ServicePage";

const commonProcess = [
  { step: "01", title: "Discovery", desc: "Deep-dive workshops on goals, data, systems and constraints." },
  { step: "02", title: "Design", desc: "Architecture, model choice, integration plan, SLAs and IP terms." },
  { step: "03", title: "Build", desc: "Iterative delivery with weekly demos, staged environments and QA." },
  { step: "04", title: "Operate", desc: "Documentation, training, monitoring and long-term support." },
];

export const services: Record<string, ServiceContent> = {
  "agentic-ai": {
    slug: "agentic-ai",
    eyebrow: "Service · Agentic AI",
    title: "Agentic AI & workflow automation",
    intro: "We design, build and deploy custom agentic AI systems using both code and no-code platforms such as n8n — managing end-to-end lifecycle from design to production.",
    outcomes: [
      { label: "Manual work reduced", value: "60–90%" },
      { label: "Time to value", value: "4–8 wks" },
      { label: "Integrations supported", value: "400+" },
      { label: "Prod uptime target", value: "99.95%" },
    ],
    offerings: [
      "Multi-agent architectures with tool use, memory and evaluation",
      "n8n and low-code orchestration for business workflows",
      "Custom Python agent frameworks with typed tool schemas",
      "Human-in-the-loop review and audit trails",
      "Observability, cost controls and prompt regression testing",
    ],
    process: commonProcess,
    faqs: [
      { q: "Do you use no-code, code, or both?", a: "Both. We choose the right substrate per workflow — n8n for glue, custom code where control, reliability or scale demands it." },
      { q: "How do you handle model choice?", a: "We benchmark on your own tasks and data, not on public leaderboards. Cost, latency and reliability are first-class." },
      { q: "Who owns the IP?", a: "You do. Ownership terms are defined in the signed agreement before work begins." },
    ],
  },
  "generative-ai": {
    slug: "generative-ai",
    eyebrow: "Service · Generative AI",
    title: "Generative AI systems",
    intro: "Fine-tuned LLMs, retrieval-augmented generation and production-grade GenAI applications tailored to your data and domain.",
    outcomes: [
      { label: "Retrieval accuracy", value: "94%+" },
      { label: "Hallucination reduction", value: "70%" },
      { label: "Deployments shipped", value: "60+" },
      { label: "Avg latency", value: "<800ms" },
    ],
    offerings: [
      "RAG over private corpora with hybrid retrieval",
      "Domain-tuned models via LoRA / QLoRA fine-tuning",
      "Guardrails, output validation and safety layers",
      "Prompt engineering, evaluation harnesses and CI",
      "Cost-aware routing across model providers",
    ],
    process: commonProcess,
    faqs: [
      { q: "Which model providers?", a: "OpenAI, Anthropic, Google, Meta and self-hosted open-weight models. We are provider-agnostic." },
      { q: "Where does data live?", a: "In your infrastructure or ours, based on your compliance requirements. We support on-prem deployments." },
      { q: "How do you evaluate?", a: "Task-specific eval sets, LLM-as-judge with human calibration and regression testing on every change." },
    ],
  },
  "robotics": {
    slug: "robotics",
    eyebrow: "Service · Robotics",
    title: "Robotics for business & industry",
    intro: "Custom robotics engineered for industrial and business automation — from robotic vision QA to autonomous material handling.",
    outcomes: [
      { label: "Cycle time reduction", value: "40–75%" },
      { label: "Defect rate cut", value: "80%+" },
      { label: "ROI window", value: "6–18 mo" },
      { label: "Systems deployed", value: "25+" },
    ],
    offerings: [
      "Robotic vision QA for manufacturing lines",
      "Autonomous material handling & warehouse robotics",
      "Custom end-effectors and sensor integration",
      "ROS / ROS2 stack development and integration",
      "Safety compliance and operator training",
    ],
    process: commonProcess,
    faqs: [
      { q: "Do you manufacture hardware?", a: "We design, prototype and partner with fabrication houses. Hardware BOM, sourcing and QA are handled by our team." },
      { q: "How is safety handled?", a: "Every deployment ships with a safety review, emergency-stop hardware and operator SOPs." },
      { q: "Support after delivery?", a: "Yes — long-term maintenance contracts with defined SLAs are part of every robotics engagement." },
    ],
  },
  "chatbots": {
    slug: "chatbots",
    eyebrow: "Service · AI Chatbots",
    title: "AI chatbot support systems",
    intro: "We integrate advanced chatbots into existing or upcoming websites and apps, custom-trained on your data with end-to-end API integration.",
    outcomes: [
      { label: "First-response time", value: "<3s" },
      { label: "Ticket deflection", value: "45–70%" },
      { label: "CSAT lift", value: "+22 pts" },
      { label: "Languages", value: "50+" },
    ],
    offerings: [
      "Custom training on knowledge bases, docs and CRM data",
      "Human handoff with full conversation context",
      "CRM, helpdesk and payment API integrations",
      "Analytics dashboards and conversation review tools",
      "Multi-channel: web, WhatsApp, mobile, voice",
    ],
    process: commonProcess,
    faqs: [
      { q: "Can it use our internal APIs?", a: "Yes. We handle the end-to-end integration including auth, rate limits and error handling." },
      { q: "Multilingual support?", a: "Yes — the chatbot can respond natively in 50+ languages." },
      { q: "Data privacy?", a: "Your data stays in your environment or ours per contract. We support on-prem and private-cloud deployments." },
    ],
  },
  "data-science": {
    slug: "data-science",
    eyebrow: "Service · Data Science",
    title: "Data science & analytics",
    intro: "Comprehensive consulting, development and deployment of data pipelines, dashboards and business analysis — led by senior data scientists.",
    outcomes: [
      { label: "Senior data scientists", value: "15+" },
      { label: "Dashboards shipped", value: "200+" },
      { label: "Pipelines maintained", value: "90+" },
      { label: "Data volume/mo", value: "8 PB" },
    ],
    offerings: [
      "Data warehouse / lakehouse architecture (Snowflake, BigQuery, Databricks)",
      "ELT pipelines with dbt, Airflow and Prefect",
      "Executive dashboards in Tableau, Looker, Metabase",
      "Predictive modeling and forecasting",
      "Data governance, quality and lineage",
    ],
    process: commonProcess,
    faqs: [
      { q: "Do you build in the cloud or on-prem?", a: "Both. We're cloud-agnostic and have deployed on AWS, GCP, Azure and on-prem." },
      { q: "Who owns the pipelines?", a: "You do. We hand off with full documentation and can run in embedded or hands-off support mode." },
      { q: "Real-time?", a: "Yes — streaming pipelines via Kafka, Flink and Materialize are part of our stack." },
    ],
  },
  "software": {
    slug: "software",
    eyebrow: "Service · Software",
    title: "Custom software development",
    intro: "Product-grade custom software for scale-ups and enterprises — designed for reliability, maintainability and long horizons.",
    outcomes: [
      { label: "Products shipped", value: "80+" },
      { label: "Avg on-time delivery", value: "96%" },
      { label: "P95 API latency", value: "<120ms" },
      { label: "Test coverage floor", value: "80%" },
    ],
    offerings: [
      "Backend services in Go, Python, Node and TypeScript",
      "Event-driven architectures and microservices",
      "Postgres, MongoDB, Redis, Kafka expertise",
      "SOC2-aware engineering practices",
      "CI/CD, observability and incident management",
    ],
    process: commonProcess,
    faqs: [
      { q: "What team size do you deploy?", a: "From 2-person strike teams to 10-person full-stack squads with a dedicated product lead." },
      { q: "Fixed price or T&M?", a: "Both are available. We recommend milestone-based fixed price for well-scoped programs." },
      { q: "Post-launch support?", a: "Yes — SRE support, on-call and feature velocity contracts are available." },
    ],
  },
  "web": {
    slug: "web",
    eyebrow: "Service · Web",
    title: "Premium web development",
    intro: "Premium web platforms with full customization — marketing sites, product web apps and internal tools built to Apple-level polish.",
    outcomes: [
      { label: "Lighthouse median", value: "97" },
      { label: "Sites shipped", value: "120+" },
      { label: "Avg TTFB", value: "<80ms" },
      { label: "A11y compliance", value: "WCAG AA" },
    ],
    offerings: [
      "React, Next.js, TanStack Start, SvelteKit",
      "Design systems, motion and micro-interactions",
      "Headless CMS integration (Contentful, Sanity, Payload)",
      "Analytics, A/B testing and conversion optimization",
      "SEO, Core Web Vitals and edge performance",
    ],
    process: commonProcess,
    faqs: [
      { q: "Do you handle design?", a: "Yes — brand, UI, motion and content design are in-house." },
      { q: "Ecommerce?", a: "Yes. Shopify, Commerce.js and headless custom builds." },
      { q: "Hosting?", a: "We deploy to Vercel, Cloudflare, AWS or your infra of choice." },
    ],
  },
  "ml-dl": {
    slug: "ml-dl",
    eyebrow: "Service · ML / DL",
    title: "Machine learning & deep learning",
    intro: "Applied ML and deep learning that ship — computer vision, NLP, forecasting and recommender systems for real business outcomes.",
    outcomes: [
      { label: "Models in production", value: "140+" },
      { label: "Avg accuracy lift", value: "+18%" },
      { label: "Time-to-model", value: "6 wks" },
      { label: "GPUs under mgmt", value: "300+" },
    ],
    offerings: [
      "Computer vision: detection, segmentation, OCR",
      "NLP: classification, entity extraction, semantic search",
      "Forecasting and time-series modeling",
      "Recommender systems and personalization",
      "MLOps: training pipelines, model registry, monitoring",
    ],
    process: commonProcess,
    faqs: [
      { q: "Do you handle labelling?", a: "Yes, via managed labelling partners with QA workflows we own." },
      { q: "Edge deployment?", a: "Yes — TensorRT, ONNX, Core ML and custom hardware inference stacks." },
      { q: "Model monitoring?", a: "Drift, data quality and performance monitoring is part of every deployment." },
    ],
  },
  "consulting": {
    slug: "consulting",
    eyebrow: "Service · Consulting",
    title: "Comprehensive consulting",
    intro: "Dedicated consulting across our full service line and our proprietary products — strategy, architecture and executive advisory.",
    outcomes: [
      { label: "CxO engagements", value: "50+" },
      { label: "Avg ROI reported", value: "6.2x" },
      { label: "Advisory hours/yr", value: "12k" },
      { label: "Repeat clients", value: "88%" },
    ],
    offerings: [
      "AI strategy and roadmap for leadership teams",
      "Technical due diligence for investors",
      "Architecture reviews and modernization plans",
      "R&D program design and grant advisory",
      "M&A and technology diligence support",
    ],
    process: commonProcess,
    faqs: [
      { q: "Engagement length?", a: "From 2-week sprints to multi-year retainers." },
      { q: "Confidentiality?", a: "All engagements are covered by a mutual NDA before any material is exchanged." },
      { q: "Who leads the work?", a: "A senior partner is accountable for every engagement." },
    ],
  },
  "training": {
    slug: "training",
    eyebrow: "Service · Training",
    title: "Industry & institutional training",
    intro: "Corporate training for enterprises and institutional training for students — delivered by industry super-experts, with proprietary modules, seminars and workshops.",
    outcomes: [
      { label: "Learners trained", value: "12,000+" },
      { label: "NPS median", value: "72" },
      { label: "Corporate clients", value: "40+" },
      { label: "Proprietary modules", value: "18" },
    ],
    offerings: [
      "Corporate cohorts: Agentic AI, GenAI, MLOps, Data Engineering",
      "Institutional programs for universities and colleges",
      "Executive briefings and board-level workshops",
      "Free public seminars and paid intensives",
      "Certification pathways with capstone projects",
    ],
    process: commonProcess,
    faqs: [
      { q: "Formats?", a: "Live cohort, self-paced, hybrid and on-site. All programs include capstones." },
      { q: "Customization?", a: "Yes — every corporate program is tailored to the client's stack and data." },
      { q: "Certificates?", a: "Verifiable certificates are issued on successful completion." },
    ],
  },
};
