/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RndRouteImport } from './routes/rnd'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PressRouteImport } from './routes/press'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BecomePartnerRouteImport } from './routes/become-partner'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesWebRouteImport } from './routes/services/web'
import { Route as ServicesTrainingRouteImport } from './routes/services/training'
import { Route as ServicesSoftwareRouteImport } from './routes/services/software'
import { Route as ServicesRoboticsRouteImport } from './routes/services/robotics'
import { Route as ServicesMlDlRouteImport } from './routes/services/ml-dl'
import { Route as ServicesGenerativeAiRouteImport } from './routes/services/generative-ai'
import { Route as ServicesDataScienceRouteImport } from './routes/services/data-science'
import { Route as ServicesConsultingRouteImport } from './routes/services/consulting'
import { Route as ServicesChatbotsRouteImport } from './routes/services/chatbots'
import { Route as ServicesAgenticAiRouteImport } from './routes/services/agentic-ai'
import { Route as LegalTermsOfUseRouteImport } from './routes/legal/terms-of-use'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal/disclaimer'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RndRoute = RndRouteImport.update({
  id: '/rnd',
  path: '/rnd',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePartnerRoute = BecomePartnerRouteImport.update({
  id: '/become-partner',
  path: '/become-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebRoute = ServicesWebRouteImport.update({
  id: '/services/web',
  path: '/services/web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTrainingRoute = ServicesTrainingRouteImport.update({
  id: '/services/training',
  path: '/services/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareRoute = ServicesSoftwareRouteImport.update({
  id: '/services/software',
  path: '/services/software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoboticsRoute = ServicesRoboticsRouteImport.update({
  id: '/services/robotics',
  path: '/services/robotics',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMlDlRoute = ServicesMlDlRouteImport.update({
  id: '/services/ml-dl',
  path: '/services/ml-dl',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGenerativeAiRoute = ServicesGenerativeAiRouteImport.update({
  id: '/services/generative-ai',
  path: '/services/generative-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesDataScienceRoute = ServicesDataScienceRouteImport.update({
  id: '/services/data-science',
  path: '/services/data-science',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsultingRoute = ServicesConsultingRouteImport.update({
  id: '/services/consulting',
  path: '/services/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesChatbotsRoute = ServicesChatbotsRouteImport.update({
  id: '/services/chatbots',
  path: '/services/chatbots',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAgenticAiRoute = ServicesAgenticAiRouteImport.update({
  id: '/services/agentic-ai',
  path: '/services/agentic-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfUseRoute = LegalTermsOfUseRouteImport.update({
  id: '/legal/terms-of-use',
  path: '/legal/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/reviews': typeof ReviewsRoute
  '/rnd': typeof RndRoute
  '/team': typeof TeamRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/generative-ai': typeof ServicesGenerativeAiRoute
  '/services/ml-dl': typeof ServicesMlDlRoute
  '/services/robotics': typeof ServicesRoboticsRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/reviews': typeof ReviewsRoute
  '/rnd': typeof RndRoute
  '/team': typeof TeamRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/generative-ai': typeof ServicesGenerativeAiRoute
  '/services/ml-dl': typeof ServicesMlDlRoute
  '/services/robotics': typeof ServicesRoboticsRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/web': typeof ServicesWebRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-partner': typeof BecomePartnerRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/partners': typeof PartnersRoute
  '/press': typeof PressRoute
  '/reviews': typeof ReviewsRoute
  '/rnd': typeof RndRoute
  '/team': typeof TeamRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/terms-of-use': typeof LegalTermsOfUseRoute
  '/services/agentic-ai': typeof ServicesAgenticAiRoute
  '/services/chatbots': typeof ServicesChatbotsRoute
  '/services/consulting': typeof ServicesConsultingRoute
  '/services/data-science': typeof ServicesDataScienceRoute
  '/services/generative-ai': typeof ServicesGenerativeAiRoute
  '/services/ml-dl': typeof ServicesMlDlRoute
  '/services/robotics': typeof ServicesRoboticsRoute
  '/services/software': typeof ServicesSoftwareRoute
  '/services/training': typeof ServicesTrainingRoute
  '/services/web': typeof ServicesWebRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-partner'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/partners'
    | '/press'
    | '/reviews'
    | '/rnd'
    | '/team'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-use'
    | '/services/agentic-ai'
    | '/services/chatbots'
    | '/services/consulting'
    | '/services/data-science'
    | '/services/generative-ai'
    | '/services/ml-dl'
    | '/services/robotics'
    | '/services/software'
    | '/services/training'
    | '/services/web'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-partner'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/partners'
    | '/press'
    | '/reviews'
    | '/rnd'
    | '/team'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-use'
    | '/services/agentic-ai'
    | '/services/chatbots'
    | '/services/consulting'
    | '/services/data-science'
    | '/services/generative-ai'
    | '/services/ml-dl'
    | '/services/robotics'
    | '/services/software'
    | '/services/training'
    | '/services/web'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-partner'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/gallery'
    | '/partners'
    | '/press'
    | '/reviews'
    | '/rnd'
    | '/team'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/terms'
    | '/legal/terms-of-use'
    | '/services/agentic-ai'
    | '/services/chatbots'
    | '/services/consulting'
    | '/services/data-science'
    | '/services/generative-ai'
    | '/services/ml-dl'
    | '/services/robotics'
    | '/services/software'
    | '/services/training'
    | '/services/web'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomePartnerRoute: typeof BecomePartnerRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PartnersRoute: typeof PartnersRoute
  PressRoute: typeof PressRoute
  ReviewsRoute: typeof ReviewsRoute
  RndRoute: typeof RndRoute
  TeamRoute: typeof TeamRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalTermsOfUseRoute: typeof LegalTermsOfUseRoute
  ServicesAgenticAiRoute: typeof ServicesAgenticAiRoute
  ServicesChatbotsRoute: typeof ServicesChatbotsRoute
  ServicesConsultingRoute: typeof ServicesConsultingRoute
  ServicesDataScienceRoute: typeof ServicesDataScienceRoute
  ServicesGenerativeAiRoute: typeof ServicesGenerativeAiRoute
  ServicesMlDlRoute: typeof ServicesMlDlRoute
  ServicesRoboticsRoute: typeof ServicesRoboticsRoute
  ServicesSoftwareRoute: typeof ServicesSoftwareRoute
  ServicesTrainingRoute: typeof ServicesTrainingRoute
  ServicesWebRoute: typeof ServicesWebRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rnd': {
      id: '/rnd'
      path: '/rnd'
      fullPath: '/rnd'
      preLoaderRoute: typeof RndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-partner': {
      id: '/become-partner'
      path: '/become-partner'
      fullPath: '/become-partner'
      preLoaderRoute: typeof BecomePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web': {
      id: '/services/web'
      path: '/services/web'
      fullPath: '/services/web'
      preLoaderRoute: typeof ServicesWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/training': {
      id: '/services/training'
      path: '/services/training'
      fullPath: '/services/training'
      preLoaderRoute: typeof ServicesTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software': {
      id: '/services/software'
      path: '/services/software'
      fullPath: '/services/software'
      preLoaderRoute: typeof ServicesSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/robotics': {
      id: '/services/robotics'
      path: '/services/robotics'
      fullPath: '/services/robotics'
      preLoaderRoute: typeof ServicesRoboticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ml-dl': {
      id: '/services/ml-dl'
      path: '/services/ml-dl'
      fullPath: '/services/ml-dl'
      preLoaderRoute: typeof ServicesMlDlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/generative-ai': {
      id: '/services/generative-ai'
      path: '/services/generative-ai'
      fullPath: '/services/generative-ai'
      preLoaderRoute: typeof ServicesGenerativeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/data-science': {
      id: '/services/data-science'
      path: '/services/data-science'
      fullPath: '/services/data-science'
      preLoaderRoute: typeof ServicesDataScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consulting': {
      id: '/services/consulting'
      path: '/services/consulting'
      fullPath: '/services/consulting'
      preLoaderRoute: typeof ServicesConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/chatbots': {
      id: '/services/chatbots'
      path: '/services/chatbots'
      fullPath: '/services/chatbots'
      preLoaderRoute: typeof ServicesChatbotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/agentic-ai': {
      id: '/services/agentic-ai'
      path: '/services/agentic-ai'
      fullPath: '/services/agentic-ai'
      preLoaderRoute: typeof ServicesAgenticAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-use': {
      id: '/legal/terms-of-use'
      path: '/legal/terms-of-use'
      fullPath: '/legal/terms-of-use'
      preLoaderRoute: typeof LegalTermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomePartnerRoute: BecomePartnerRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PartnersRoute: PartnersRoute,
  PressRoute: PressRoute,
  ReviewsRoute: ReviewsRoute,
  RndRoute: RndRoute,
  TeamRoute: TeamRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalTermsOfUseRoute: LegalTermsOfUseRoute,
  ServicesAgenticAiRoute: ServicesAgenticAiRoute,
  ServicesChatbotsRoute: ServicesChatbotsRoute,
  ServicesConsultingRoute: ServicesConsultingRoute,
  ServicesDataScienceRoute: ServicesDataScienceRoute,
  ServicesGenerativeAiRoute: ServicesGenerativeAiRoute,
  ServicesMlDlRoute: ServicesMlDlRoute,
  ServicesRoboticsRoute: ServicesRoboticsRoute,
  ServicesSoftwareRoute: ServicesSoftwareRoute,
  ServicesTrainingRoute: ServicesTrainingRoute,
  ServicesWebRoute: ServicesWebRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
